# Generated by Django 3.0.4 on 2020-04-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_dish_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name_plural': 'dishes'},
        ),
    ]
