# Generated by Django 3.0.4 on 2020-05-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0005_dish_recipe_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dishes', models.ManyToManyField(to='dish.Dish')),
            ],
        ),
    ]
