# Generated by Django 3.0.4 on 2020-05-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0007_populate_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='dishes',
            field=models.ManyToManyField(related_name='ingredients', to='dish.Dish'),
        ),
    ]
