# Generated by Django 3.0.4 on 2020-05-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0009_order_ingredients_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='section',
            field=models.CharField(blank=True, choices=[('meat', 'Meat counter'), ('veg', 'Fruit and veg')], max_length=10),
        ),
    ]
