# Generated by Django 3.1.4 on 2020-12-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0011_dish_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='storage',
            field=models.CharField(blank=True, choices=[('freezer', 'Freezer'), ('fridge', 'Fridge'), ('larder', 'Larder')], max_length=10),
        ),
    ]
