# Generated by Django 3.1.13 on 2022-04-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0012_ingredient_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
