# Generated by Django 3.0.4 on 2020-04-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dish', '0005_dish_recipe_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.Dish')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.CheckConstraint(check=models.Q(('completed_at', None), ('cancelled_at', None), _connector='OR'), name='complete_cancel_exclusion'),
        ),
    ]
