# Generated by Django 3.0.4 on 2020-05-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_add_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='plan.Batch'),
        ),
    ]
